ex1: checkBox.o checkBoxList.o comp.o handleIO.o Label.o textBox.o main.o
	g++ checkBox.o checkBoxList.o comp.o handleIO.o Label.o textBox.o main.o -o ex1

checkBox.o: checkBox.cpp
	g++ -c checkBox.cpp

checkBoxList.o: checkBoxList.cpp
	g++ -c checkBoxList.cpp

comp.o: comp.cpp
	g++ -c comp.cpp

handleIO.o: handleIO.cpp
	g++ -c handleIO.cpp

Label.o: Label.cpp
	g++ -c Label.cpp

textBox.o: textBox.cpp
	g++ -c textBox.cpp

main.o: main.cpp
	g++ -c main.cpp